-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Platform"
(
    platform_id integer NOT NULL,
    platform_name text NOT NULL,
    PRIMARY KEY (platform_id)
);

CREATE TABLE IF NOT EXISTS public."Date"
(
    date_id integer NOT NULL,
    date date NOT NULL,
    PRIMARY KEY (date_id)
);

CREATE TABLE IF NOT EXISTS public."KPI"
(
    dqs numeric(5, 2) NOT NULL,
    platform integer NOT NULL,
    date integer NOT NULL,
    PRIMARY KEY (platform, date)
);

CREATE TABLE IF NOT EXISTS public."Bottom_Users"
(
    username text NOT NULL,
    karma_score integer,
    is_verified text,
    created_at date,
    user_followers integer,
    rank integer NOT NULL,
    platform integer NOT NULL,
    date integer NOT NULL,
    PRIMARY KEY (platform, date, rank)
);

CREATE TABLE IF NOT EXISTS public."Top_Users"
(
    username text NOT NULL,
    karma_score integer,
    is_verified text,
    created_at date,
    user_followers integer,
    rank integer NOT NULL,
    platform integer NOT NULL,
    date integer NOT NULL,
    PRIMARY KEY (platform, date, rank)
);

CREATE TABLE IF NOT EXISTS public."Post_Metrics"
(
    stories integer NOT NULL,
    comments integer NOT NULL,
    jobs integer NOT NULL,
    polls integer NOT NULL,
    platform integer NOT NULL,
    date integer NOT NULL,
    PRIMARY KEY (platform, date)
);

CREATE TABLE IF NOT EXISTS public."Top_Posts"
(
    post_id text NOT NULL,
    author_username text NOT NULL,
    content_text text,
    created_at date,
    post_type text,
    score integer,
    year text,
    month text,
    day text,
    rank integer NOT NULL,
    platform integer NOT NULL,
    date integer NOT NULL,
    PRIMARY KEY (platform, date, rank)
);

CREATE TABLE IF NOT EXISTS public."User_Metrics"
(
    users integer NOT NULL,
    platform integer NOT NULL,
    date integer NOT NULL,
    PRIMARY KEY (platform, date)
);

ALTER TABLE IF EXISTS public."KPI"
    ADD FOREIGN KEY (platform)
    REFERENCES public."Platform" (platform_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."KPI"
    ADD FOREIGN KEY (date)
    REFERENCES public."Date" (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bottom_Users"
    ADD FOREIGN KEY (platform)
    REFERENCES public."Platform" (platform_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bottom_Users"
    ADD FOREIGN KEY (date)
    REFERENCES public."Date" (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Top_Users"
    ADD FOREIGN KEY (platform)
    REFERENCES public."Platform" (platform_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Top_Users"
    ADD FOREIGN KEY (date)
    REFERENCES public."Date" (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Post_Metrics"
    ADD FOREIGN KEY (platform)
    REFERENCES public."Platform" (platform_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Post_Metrics"
    ADD FOREIGN KEY (date)
    REFERENCES public."Date" (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Top_Posts"
    ADD FOREIGN KEY (platform)
    REFERENCES public."Platform" (platform_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Top_Posts"
    ADD FOREIGN KEY (date)
    REFERENCES public."Date" (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."User_Metrics"
    ADD FOREIGN KEY (platform)
    REFERENCES public."Platform" (platform_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."User_Metrics"
    ADD FOREIGN KEY (date)
    REFERENCES public."Date" (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;